FROM python:3.8.2
COPY ./RobotMeQ/Configs/pip.conf root/.pip/pip.conf
COPY ./RobotMeQ /home/RobotMeQ
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN pip install -r /home/RobotMeQ/Configs/requirements.txt --trusted-host mirrors.aliyun.com
